export const MAX_PAGE_SIZE = 100;

export const PAGINATION = {
  OFFSET_DEFAULT_PAGE_SIZE: 10,
  MAX_PAGE_SIZE,
};

export const CHALLENGE_LIMITS = {
  TITLE_MAX_LENGTH: 100,
  DESCRIPTION_MIN_LENGTH: 10,
  DESCRIPTION_MAX_LENGTH: 500,
  DECLINE_REASON_MAX_LENGTH: 255,

  CURSOR_LIST_LIMIT_DEFAULT: 20,
  CURSOR_LIST_LIMIT_MAX: MAX_PAGE_SIZE,
};

export const COMMENT_LIMITS = {
  CONTENT_MAX_LENGTH: 1000,
};

export const WORK_LIMITS = {
  CONTENT_MAX_LENGTH: 5000,
};

export const ADMIN_LIMITS = {
  DECLINE_REASON_MAX_LENGTH: 200,
};
